node {
        stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
    }
    try {
        stage('Deploy') {
            docker.image('cdrx/pyinstaller-linux:python2').inside {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
        }
    } finally {
        archiveArtifacts 'dist/add2vals'
        sleep(time: 1, unit: 'MINUTES')
    }
}

