node {
    docker.image('node:ea7f826b1553').inside('-p 3000:3000') {
        withEnv(['CI = true']) {
            stage('Manual Approval') {
                input message: 'Lanjutkan ke tahap Deploy?'
            }
            stage('Deploy') {
                sh './jenkins/scripts/deliver.sh'
                sleep(time: 1, unit: 'MINUTES')
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
